### ISSUE TITLE
Perform a full QA test on an Odroid C2 image

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/liquidinvestigations#233]
* [x] finish work on the odroid MVP (https://github.com/liquidinvestigations/liquidinvestigations/issues/221)
* [x] update user manual (https://github.com/liquidinvestigations/liquidinvestigations/issues/188)
* [ ] ~write out instructions for QA testing on the Odroid C2 (https://github.com/liquidinvestigations/liquidinvestigations/issues/251)~
* [ ] ~run through the QA instructions and report results~

**Comment by mgax** [comment]
@mrc-toader I've just updated the hardware list: https://github.com/liquidinvestigations/docs/blob/master/manual/Readme.md#hardware-requirements

**Comment by mgax** [comment]
@mrc-toader There goes another update to the docs. Please make a run through the test script and report any issues you find.

**Comment by mrc-toader** [comment]
I did a partial test, apps not working. Waiting for a new build.

**Comment by mgax** [comment]
Closing; there is a separate issue for the instructions.
